FROM amazoncorretto:17-alpine-jdk

WORKDIR /app
COPY ./build/libs/mate-0.0.1-SNAPSHOT.jar /app/mate-app.jar

ENV TZ=Asia/Seoul

CMD ["java", "-jar", "-Dspring.profiles.active=dev", "-Djava.net.preferIPv4Stack=true", "mate-app.jar"]
