server:
port:8080
#kakao api key ?
kakao.api.key=bc37962ff79968f6da8c4e55f765efad
kakao.redirect.uri=http://localhost:8080/api/v1/auth/login/kakao
#?? ??? url ??  jsessionid ?? ??
server.servlet.session.tracking-modes=cookie
spring.web.resources.static-locations=classpath:/static/
#jwt:
#expiration_time: 86400000 #1?
#secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkdwqSAW