server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s

  sql:
    init:
      mode: never

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/mate-local-db
    username: mate-local-user
    password: mate-local-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true
        highlight_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false


  config:
    import: optional:file:.env[.properties]

  cookie:
    maxage: 987654321
    path: /
    samesite: Lax
    domain: localhost
    secure: false
    http-only: true

  security:
    oauth2:
      success-redirect: ${KAKAO_SUCCESS_REDIRECT}
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    secret-key: ${JWT_SECRET}
    access-expired: 987654321
    refresh-expired: 987654321
