server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/mate-local-db
    username: mate-local-user
    password: mate-local-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #    hibernate:
    #      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false

  jwt:
    expiration_time: 86400000 #1일
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

  kakao:
    api.key: bc37962ff79968f6da8c4e55f765efad
    redirect.uri: http://localhost:8080/api/v1/auth/login/kakao

logging:
  level:
    org.hibernate.SQL: debug

